---

- fail:
    msg: 'Bailing out. This play requires "zookeeper_hosts"'
  when: zookeeper_hosts is not defined

- fail:
    msg: 'Bailing out. This play requires "cassandra_hosts"'
  when: cassandra_hosts is not defined

- name: Configure midonet cluster config file
  template:
    src: 'midonet.conf.j2'
    dest: '/etc/midonet/midonet.conf'
  notify: Restart midonet cluster

- name: Set loglevel in midonet-cluster.conf
  replace:
    dest: '/etc/midonet-cluster/logback.xml'
    regexp: '    <root level=".*">'
    replace: '    <root level="DEBUG">'
  notify: Restart midonet cluster
  when: midonet_cluster_loglevel == 'debug'

- name: mn-conf default template
  template:
    src: 'default.template.j2'
    dest: '/etc/midonet/default.template'
    owner: 'root'
    group: 'root'

- name: Apply default mn-conf template (for all nodes)
  shell: 'cat /etc/midonet/default.template | mn-conf set -t default'
  changed_when: False
  delay: 10
  register: midonet_cluster_mn_conf_set_default_template
  retries: 5
  until: midonet_cluster_mn_conf_set_default_template|success

- block:
    - name: mn-conf metadata template
      template:
        src: 'metadata.template.j2'
        dest: '/etc/midonet/metadata.template'
        owner: 'root'
        group: 'root'

    - name: Apply metadata mn-conf template
      shell: 'cat /etc/midonet/metadata.template | mn-conf set -t default'
      changed_when: False
      delay: 10
      register: midonet_cluster_mn_conf_set_metadata_template
      retries: 5
      until: midonet_cluster_mn_conf_set_metadata_template|success
  when: midonet_cluster_enable_metadata|default(False)|bool

- block:
    - name: mn-conf mem-cluster template
      template:
        dest: '/etc/midonet/mem-cluster.template'
        group: 'root'
        mode: 0644
        owner: 'root'
        src: 'mem-cluster.template.j2'

    - name: Apply mem-cluster mn-conf template
      shell: 'cat /etc/midonet/mem-cluster.template | mn-conf set -t default'
      changed_when: False
      delay: 10
      register: midonet_cluster_mn_conf_set_mem_cluster_template
      retries: 5
      until: midonet_cluster_mn_conf_set_mem_cluster_template|success
  when: midonet_cluster_mem_enabled

- name: Configure MAX_HEAP_SIZE for JVM
  lineinfile:
    dest: '/etc/midonet-cluster/midonet-cluster-env.sh'
    regexp: '^MAX_HEAP_SIZE='
    line: 'MAX_HEAP_SIZE="{{ midonet_cluster_max_heap_size }}"'
    state: present
  notify: Restart midonet cluster

- name: Configure HEAP_NEWSIZE for JVM
  lineinfile:
    dest: '/etc/midonet-cluster/midonet-cluster-env.sh'
    regexp: '^HEAP_NEWSIZE='
    line: 'HEAP_NEWSIZE="{{ midonet_cluster_heap_newsize }}"'
    state: present
  notify: Restart midonet cluster
